### ISSUE TITLE
High Commander issues

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#21]
Не удается отдать приказ группам. После выделения группы на карте и клика ЛКМ в другом месте, вейпоинт не создается. После клика на группе и выпбора RemoteControl, ничего не происходит.
В логе клиента замечены следующие ошибки

**Демобилизация групп**
`8:20:04 Error in expression <itSel != -1) then {
_groupCount = count _groups;
_group = _groups # _curUnitSel;>
 8:20:04   Error position: <_groups;
_group = _groups # _curUnitSel;>
 8:20:04   Error Неопределенная переменная в выражении: _groups
 8:20:04 File Client\Player\GUI\TeamMenu\fn_displayTeamMenu.sqf [WFCL_fnc_displayTeamMenu]..., line 146`

Командиром меня назначил предыдущий ком.

**Comment by Spayker** [comment]
fixed
