### ISSUE TITLE
HIGH COMMANDER: группы остаются в игре после выхода игрока

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#4]
После выхода игрока из игры, группы всё равно остаются в игре. По возвращению игрок может выделять их, но приказы уже не принимаются, нельзя создать вейпоинт.

**Comment by Spayker** [comment]
Из-за ограничений в АПИ high command решить проблему с минимальными потерями не удалось. В репозиторий ушел фикс, который убирает все созданные группы, если игрок-командир ушел с сервера.
