### ISSUE TITLE
заводы взрываются 

### ISSUE THREAD

**Issue by Emperor2021** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#42]
![image](https://user-images.githubusercontent.com/80774634/132976878-24efbbf4-0ac0-4e26-bbe6-ba1f6d1789dc.png)
скорее всего из смены объекта когда он окончательно построен. 
в этом случае появляется танк в камне тем самым он взрывается.

**Comment by EgoBrainProgrammer** [comment]
Ресурсы возвращаются, игрок должен внимательней выбирать места постройки.
