### ISSUE TITLE
криво ставятся заводы 

### ISSUE THREAD

**Issue by Emperor2021** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#45]
![image](https://user-images.githubusercontent.com/80774634/136318370-2ab55eb8-3f96-4a6b-96ff-115ef375c450.png)
![image](https://user-images.githubusercontent.com/80774634/136318440-e13b48a2-adfb-424f-83b7-7e4b65497b89.png)

после окончания строительство получается такая херн, здания в здании

**Comment by EgoBrainProgrammer** [comment]
Баг не воспроизводится.
