### ISSUE TITLE
взрываются заводы 

### ISSUE THREAD

**Issue by Emperor2021** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#46]
![image](https://user-images.githubusercontent.com/80774634/136318767-71e8458c-2de7-4f0d-9392-ec5c889fc0ce.png)
![image](https://user-images.githubusercontent.com/80774634/136318807-47d4cfd0-ed0c-4ee6-9501-2ff374c9104a.png)
координаты 091114 
карта алтис, время 07.10.2021 07:08

**Comment by EgoBrainProgrammer** [comment]
https://github.com/EgoBrainProgrammer/ARMA3WARFARE_ISSUES/issues/42
