### ISSUE TITLE
постройка стратегических объектов 

### ISSUE THREAD

**Issue by Emperor2021** [EgoBrainProgrammer/ARMA3WARFARE_ISSUES#55]
![image](https://user-images.githubusercontent.com/80774634/146663770-cd25130e-6d59-43e8-a385-de82ca66edd9.png)
![image](https://user-images.githubusercontent.com/80774634/146663878-1e839d91-87fd-41db-8486-3c85c0d32ef2.png)

при постройки штаб военного склада, строится танковый завод ))))))))))))

**Comment by EgoBrainProgrammer** [comment]
Исправлено.
Fixed.
